# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_side.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x63lient_side.proto"<\n\x05Paper\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0c\n\x04hash\x18\x03 \x01(\x03\x12\x0f\n\x07\x66\x65\x61ture\x18\x04 \x01(\t"\x1e\n\x04Year\x12\x16\n\x06papers\x18\x01 \x03(\x0b\x32\x06.Paper""\n\nConference\x12\x14\n\x05years\x18\x01 \x03(\x0b\x32\x05.Year"(\n\x04\x44\x61ta\x12 \n\x0b\x63onferences\x18\x01 \x03(\x0b\x32\x0b.Conferenceb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "client_side_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PAPER._serialized_start = 21
    _PAPER._serialized_end = 81
    _YEAR._serialized_start = 83
    _YEAR._serialized_end = 113
    _CONFERENCE._serialized_start = 115
    _CONFERENCE._serialized_end = 149
    _DATA._serialized_start = 151
    _DATA._serialized_end = 191
# @@protoc_insertion_point(module_scope)
